<script src="scripts/galleryEffect.js"></script>

<section class="slide artiste-header" id="artisteHeader" data-type="background" data-speed="3" style="background-image: url('<?php echo $card['Card'] ?>');"></section>
<section class="artist-content">
    <div class="artist-name">
        <h3> <?php echo $artiste['Name'];  ?> </h3>
    </div>
    <div class="artist-description">
        <p><?php echo $artiste['Description'] ?></p>
    </div>
    <div class="albums-container">
        <?php foreach($albums as $album): ?>
        <div class="album-card" style="background-image: url('<?php echo $album['Artwork'] ?>'); background-position: left; background-repeat: no-repeat; background-size: cover">
                <div class="album-content">

                </div>
        </div>
        <?php endforeach; ?>
    </div>
        <?php foreach($songs as $song): ?>
        <p> <?php echo $song['Title']; ?> </p>
        <?php endforeach; ?>
    <div class="options gallery">
        <?php foreach($albums as $album): ?>
        <div class="option active" style="background-image: url('<?php echo $album['Artwork'] ?>'); background-position: center; background-repeat: no-repeat; background-size: cover" onclick="gallery(event)">
            <div class="shadow"></div>
            <div class="label">
                <div class="icon">
                    <i class="fas fa-walking"></i>
                </div>
                <div class="info">
                    <div class="main">
                        <?php echo $album['Title'] ?>
                    </div>
                </div>
            </div>
        </div>
        <?php endforeach; ?>





    </div>
</section>