<section class="slide artiste-header" id="artisteHeader" data-type="background" data-speed="3" style="background-image: url('<?php echo $card['Card'] ?>');"></section>
<section class="artist-content">
    <div class="artist-name">
        <h3> <?php echo $artiste['Name'];  ?> </h3>
    </div>
    <div class="artist-description">
        <p><?php echo $artiste['Description'] ?></p>
    </div>
    <div class="albums-container">
            <div class="album-artwork">

            </div>
            <div class="album-songs">
            </div>
    </div>



</section>