<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="assets/css/reset.css">
    <script src="https://kit.fontawesome.com/5138cb0aad.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="assets/css/main.css">
    <title>Document</title>
</head>
<body>
    <header class="header" id="header">
        <div class="header-desktop">
            <div class="bandeau">
                <p>Bacon Record, le label musical des porcs!</p>
            </div>
            <div class="logo-navbar-container">
                <div class="logo-container">
                    <a href="#">
                        <i class="fas fa-piggy-bank" id="logo"></i>
                    </a>
                </div>
                <div class="navbar">
                    <ul class="main-menu">
                        <li>
                            <a href="index.php">Home</a>
                        </li>
                        <li class="catalogue-hover">
                            <a href="#">Catalogue</a>
                            <ul class="sub-menu">
                                <?php foreach($artistes as $artiste): ?>
                                <li><a href="#"><?php echo $artiste['Name'] ?></a></li>
                                <?php endforeach; ?>
                            </ul>
                        </li>
                        <li>
                            <a href="#">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

    </header>
    <header class="header-mobile">
        <div class="bandeau">
            <p>Bacon Record, le label musical des porcs!</p>
        </div>
        <div class="logo-container-mobile">
            <i class="fas fa-piggy-bank" id="logo" onclick="openMenu()"></i>
        </div>
        <div class="navbar-mobile" id="navbarMobile">
            <ul class="ul-navbar-mobile">
                <?php foreach($artistes as $artiste): ?>
                <li><a href="#"><?php echo $artiste['Name'] ?></a></li>
                <?php endforeach; ?>
            </ul>
        </div>
    </header>
    <main class="main">
        <?php include $template.'.phtml' ?>
    </main>
    <footer class="footer">
        <div class="social-container">
            <ul>
                <li><a href="#"><i class="fab fa-youtube"></i></a></li>
                <li><a href="#"><i class="fab fa-instagram-square"></i></a></li>
                <li><a href="#"><i class="fab fa-facebook"></i></a></li>
            </ul>
        </div>
        <div class="newsletter-container">
            <form method="POST">
                <label for="newsletter">Newsletter</label>
                <input type="text" name="newsletter" id="newsletter" placeholder="exemple@exemple.com" required>
                <input type="submit" value="Envoyer" id="submitBtn">
            </form>
        </div>
    </footer>
    <script src="scripts/parallaxEffect.js"></script>
    <script src="scripts/navbarEffect.js"></script>
    <script src="scripts/newsContainerEffect.js"></script>
</body>
</html>