<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="assets/css/reset.css">
    <script src="https://kit.fontawesome.com/5138cb0aad.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="assets/css/main.css">
    <title>Document</title>
</head>
<body>
    <header class="header" id="header">
        <div class="header-desktop">
            <div class="bandeau">
                <p>Bacon Record, le label musical des porcs!</p>
            </div>
            <div class="logo-navbar-container">
                <div class="logo-container">
                    <a href="index.php">
                        <i class="fas fa-piggy-bank" id="logo"></i>
                    </a>
                </div>
                <div class="navbar">
                    <ul class="main-menu">
                        <li>
                            <a href="index.php">Home</a>
                        </li>
                        <li class="catalogue-hover">
                            <a href="#">Catalogue</a>
                            <ul class="sub-menu">
                                <?php foreach($artistes as $art): ?>
                                <li><a href="artiste.php?id=<?php echo $art['Id']?>"><?php echo $art['Name']?></a></li>
                                <?php endforeach; ?>
                            </ul>
                        </li>
                        <li>
                            <a href="#">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <?php if(isset($newsLetterRecorded)) { ?>
            <div id="newsLetterRecorded" style="background-color: rgba(148, 189, 143, 0.8);">
                <p style="color: rgba(28, 116, 17, 1); font-size: 18px;"><?php echo $newsLetterRecorded ?></p>
            </div>
        <?php } ?>
        <?php if(isset($errEmailExist)) { ?>
            <div id="emailExist" style="background-color: rgba(230, 76, 76, 0.74);">
                <p style="color: rgba(116, 17, 17, 1); font-size: 18px;"><?php echo $errEmailExist ?></p>
            </div>
        <?php } ?>
    </header>
    <header class="header-mobile">
        <div class="bandeau">
            <p>Bacon Record, le label musical des porcs!</p>
        </div>
        <div class="logo-container-mobile">
            <i class="fas fa-piggy-bank" id="logo" onclick="openMenu()"></i>
        </div>
        <div class="navbar-mobile" id="navbarMobile">
            <ul class="ul-navbar-mobile">
                <?php foreach($artistes as $art): ?>
                <li><a href="artiste.php?id=<?php echo $art['Id'] ?>&titre=<?php echo $art['Name']  ?>"><?php echo $art['Name'] ?></a></li>
                <?php endforeach; ?>
            </ul>
        </div>
    </header>
    <main class="main">
        <?php include $template.'.phtml' ?>
    </main>
    <footer class="footer">
        <div class="social-container">
            <ul>
                <li><a href="#"><i class="fab fa-youtube"></i></a></li>
                <li><a href="#"><i class="fab fa-instagram-square"></i></a></li>
                <li><a href="#"><i class="fab fa-facebook"></i></a></li>
            </ul>
        </div>
        <div class="newsletter-container">
            <form method="POST" id="newsletterForm">
                <label for="newsletterInput">Newsletter</label>
                <input type="text" name="newsletter" id="newsletterInput" placeholder="exemple@exemple.com" onkeyup="enableNewsletter()">
                <input type="submit" value="Envoyer" name="submitNewsLetter" id="submitNewsLetter" disabled>
            </form>
        </div>
    </footer>
    <script src="scripts/parallaxEffect.js"></script>
    <script src="scripts/navbarEffect.js"></script>
    <script src="scripts/newsContainerEffect.js"></script>
<!--    <script src="scripts/ajaxRequestNewsLetter.js"></script>-->
    <script src="scripts/newsletterFormValidation.js"></script>
</body>
</html>